project:
  type: website

website: 
  page-navigation: true
  search: true
  site-url: https://beaconsproject.github.io/caribou_workbook
  repo-url: https://github.com/beaconsproject/caribou_workbook 
  repo-actions: [edit, issue]
  
  sidebar:
    title: "Caribou Analysis Workbook"
    pinned: true
    align: left
    
    style: "docked"
    search: false
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
      - ---
      - section: "Little Rancheria"
        contents:
        - href: little_rancheria/overview.qmd
          text: Overview
        - href: little_rancheria/ranges.qmd
          text: Seasonal ranges
        - href: little_rancheria/corridors.qmd
          text: Seasonal corridors
      - ---
      - section: "Appendices"
        contents:
        - href: appendices/segments.qmd
          text: Segmenting data
        - href: appendices/ranges.qmd
          text: Estimating ranges
        - href: appendices/corridors.qmd
          text: Mapping corridors
        - href: appendices/covariates.qmd
          text: Habitat covariates
        - href: appendices/hsf.qmd
          text: Habitat selection

format:
  html:
    theme: cosmo
    code-copy: true
    code-fold: true
    code-overflow: wrap
    toc: true
    css: styles.css

execute:
  freeze: auto
