project:
  type: website
  output-dir: docs

website: 
  page-navigation: true
  search: true
  site-url: https://beaconsproject.github.io/caribou_workbook
  repo-url: https://github.com/beaconsproject/caribou_workbook 
  repo-actions: [edit, issue]
  
  sidebar:
    title: "Caribou Analysis Workbook"
    pinned: true
    align: left
    
    style: "docked"
    search: false
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
      - href: workflow.qmd
        text: Workflow
      - ---
      - section: "Methods"
        contents:
        - href: methods/segments.qmd
          text: Segmenting data
        - href: methods/ranges.qmd
          text: Estimating ranges
        - href: methods/corridors.qmd
          text: Mapping corridors
        - href: methods/covariates.qmd
          text: Habitat covariates
        - href: methods/hsf.qmd
          text: Habitat selection
      - ---
      - section: Herds
        contents:
        - section: "Little Rancheria"
          contents:
          - href: little_rancheria/overview.qmd
            text: Overview
          - href: little_rancheria/ranges.qmd
            text: Seasonal ranges
          - href: little_rancheria/segments.qmd
            text: Migration segments
          - href: little_rancheria/corridors.qmd
            text: Migration corridors
          - href: little_rancheria/rsf.qmd
            text: Habitat selection
        - section: "Wolf Lake"
          contents:
          - href: wolf_lake/overview.qmd
            text: Overview
        - section: "Horseranch"
          contents:
          - href: horseranch/overview.qmd
            text: Overview
      - ---
      - section: "Appendices"
        contents:
        - href: appendices/issues.qmd
          text: Issues
        - href: appendices/references.qmd
          text: References
        - href: apps.qmd
          text: Apps & dashboards

format:
  html:
    theme: cosmo
    code-copy: true
    code-fold: true
    code-overflow: wrap
    toc: true
    css: styles.css

execute:
  freeze: auto
